# Generated by Django 4.2.6 on 2023-10-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
