# Generated by Django 4.2.6 on 2024-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('lyricist', models.CharField(max_length=255)),
                ('music_director', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Remix', 'Remix'), ('Pop', 'Pop'), ('DJ', 'DJ'), ('hippop', 'hippop')], max_length=50)),
                ('lyrics', models.TextField()),
                ('is_free', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('song_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cover_image', models.ImageField(upload_to='music_covers/')),
                ('music_file', models.FileField(upload_to='music_files/')),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
    ]
